# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/clion-2017.2.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /usr/local/clion-2017.2.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paolo/src/wandstem-flash-utility

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paolo/src/wandstem-flash-utility

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/clion-2017.2.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/clion-2017.2.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paolo/src/wandstem-flash-utility/CMakeFiles /home/paolo/src/wandstem-flash-utility/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paolo/src/wandstem-flash-utility/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wandstem-flash

# Build rule for target.
wandstem-flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wandstem-flash
.PHONY : wandstem-flash

# fast build rule for target.
wandstem-flash/fast:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/build
.PHONY : wandstem-flash/fast

Device.o: Device.cpp.o

.PHONY : Device.o

# target to build an object file
Device.cpp.o:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Device.cpp.o
.PHONY : Device.cpp.o

Device.i: Device.cpp.i

.PHONY : Device.i

# target to preprocess a source file
Device.cpp.i:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Device.cpp.i
.PHONY : Device.cpp.i

Device.s: Device.cpp.s

.PHONY : Device.s

# target to generate assembly for a file
Device.cpp.s:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Device.cpp.s
.PHONY : Device.cpp.s

Program.o: Program.cpp.o

.PHONY : Program.o

# target to build an object file
Program.cpp.o:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Program.cpp.o
.PHONY : Program.cpp.o

Program.i: Program.cpp.i

.PHONY : Program.i

# target to preprocess a source file
Program.cpp.i:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Program.cpp.i
.PHONY : Program.cpp.i

Program.s: Program.cpp.s

.PHONY : Program.s

# target to generate assembly for a file
Program.cpp.s:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/Program.cpp.s
.PHONY : Program.cpp.s

XmodemPacket.o: XmodemPacket.cpp.o

.PHONY : XmodemPacket.o

# target to build an object file
XmodemPacket.cpp.o:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/XmodemPacket.cpp.o
.PHONY : XmodemPacket.cpp.o

XmodemPacket.i: XmodemPacket.cpp.i

.PHONY : XmodemPacket.i

# target to preprocess a source file
XmodemPacket.cpp.i:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/XmodemPacket.cpp.i
.PHONY : XmodemPacket.cpp.i

XmodemPacket.s: XmodemPacket.cpp.s

.PHONY : XmodemPacket.s

# target to generate assembly for a file
XmodemPacket.cpp.s:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/XmodemPacket.cpp.s
.PHONY : XmodemPacket.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/main.cpp.s
.PHONY : main.cpp.s

serial-port/6_stream/serialstream.o: serial-port/6_stream/serialstream.cpp.o

.PHONY : serial-port/6_stream/serialstream.o

# target to build an object file
serial-port/6_stream/serialstream.cpp.o:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/serial-port/6_stream/serialstream.cpp.o
.PHONY : serial-port/6_stream/serialstream.cpp.o

serial-port/6_stream/serialstream.i: serial-port/6_stream/serialstream.cpp.i

.PHONY : serial-port/6_stream/serialstream.i

# target to preprocess a source file
serial-port/6_stream/serialstream.cpp.i:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/serial-port/6_stream/serialstream.cpp.i
.PHONY : serial-port/6_stream/serialstream.cpp.i

serial-port/6_stream/serialstream.s: serial-port/6_stream/serialstream.cpp.s

.PHONY : serial-port/6_stream/serialstream.s

# target to generate assembly for a file
serial-port/6_stream/serialstream.cpp.s:
	$(MAKE) -f CMakeFiles/wandstem-flash.dir/build.make CMakeFiles/wandstem-flash.dir/serial-port/6_stream/serialstream.cpp.s
.PHONY : serial-port/6_stream/serialstream.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... wandstem-flash"
	@echo "... Device.o"
	@echo "... Device.i"
	@echo "... Device.s"
	@echo "... Program.o"
	@echo "... Program.i"
	@echo "... Program.s"
	@echo "... XmodemPacket.o"
	@echo "... XmodemPacket.i"
	@echo "... XmodemPacket.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... serial-port/6_stream/serialstream.o"
	@echo "... serial-port/6_stream/serialstream.i"
	@echo "... serial-port/6_stream/serialstream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

